name: BukkitContribEssentials
main: net.llamaslayers.minecraft.bukkitcontribessentials.BukkitContribEssentials
version: 0.1.2
description: Textures, capes, music, notifications, and more!
author: Nightgunner5
authors:
  - Afforess
softdepend:
  - BukkitContrib
website: http://forums.bukkit.org/threads/25399/
commands:
    playmusic:
        usage: /playmusic [-global] [-custom] [track]